### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by jackshouse** [WebBreacher/thematrix#4]
ImportError: cannot import name 'Adafruit_RGBmatrix' from 'rgbmatrix' 

Know a way to fix this?

**Comment by WebBreacher** [comment]
Hey there. I don't have much info about your system but you do need to install all the dependencies for the software. Looks like one is missing. Perhaps try installing/reinstalling that. 

Also, this project "worked" years ago. I'm not sure if software updates broke something since I stopped working on this.

**Comment by jackshouse** [comment]
Ya adafruit has changed things around. They hardly like to use plain
python, instead they have been transferring all to circuitpython, that way
you buy their new tech. Thanks for your reply.

**Comment by WebBreacher** [comment]
Ah...I see. Sorry about that.....best of luck!!
